# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\林晨\Desktop\聚合物裂解模拟计算实验GUI\InterfaceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 40, 860, 590))
        self.frame.setMinimumSize(QtCore.QSize(860, 590))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setText("")
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("border:none;\n"
"font: 18pt \"楷体\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/HomeIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_min.setText("")
        self.pushButton_min.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_3.addWidget(self.pushButton_min)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_close.setText("")
        self.pushButton_close.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    \n"
"    background-color: rgb(32, 81, 124);\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"幼圆\";\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_no_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_no_2.setText("")
        self.pushButton_no_2.setObjectName("pushButton_no_2")
        self.verticalLayout_2.addWidget(self.pushButton_no_2)
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.button1 = QtWidgets.QPushButton(self.frame_6)
        self.button1.setObjectName("button1")
        self.verticalLayout_2.addWidget(self.button1)
        self.button2 = QtWidgets.QPushButton(self.frame_6)
        self.button2.setObjectName("button2")
        self.verticalLayout_2.addWidget(self.button2)
        self.button3 = QtWidgets.QPushButton(self.frame_6)
        self.button3.setObjectName("button3")
        self.verticalLayout_2.addWidget(self.button3)
        self.button4 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button4.setFont(font)
        self.button4.setObjectName("button4")
        self.verticalLayout_2.addWidget(self.button4)
        self.button5 = QtWidgets.QPushButton(self.frame_6)
        self.button5.setObjectName("button5")
        self.verticalLayout_2.addWidget(self.button5)
        self.button6 = QtWidgets.QPushButton(self.frame_6)
        self.button6.setObjectName("button6")
        self.verticalLayout_2.addWidget(self.button6)
        self.pushButton_no_1 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_no_1.setText("")
        self.pushButton_no_1.setObjectName("pushButton_no_1")
        self.verticalLayout_2.addWidget(self.pushButton_no_1)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(90, 210, 448, 29))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"汉仪顺利松鹤体 简\";\n"
"border:1px solid blue;\n"
"border-radius:5px;")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.page_home)
        self.label_6.setGeometry(QtCore.QRect(90, 280, 448, 29))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"汉仪顺利松鹤体 简\";\n"
"border:1px solid blue;\n"
"border-radius:5px;")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_home)
        self.page_select = QtWidgets.QWidget()
        self.page_select.setObjectName("page_select")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_select)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.page_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        self.label_2.setStyleSheet("font: 16pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_10 = QtWidgets.QFrame(self.page_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(218, 218, 218);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pe_button = QtWidgets.QPushButton(self.frame_10)
        self.pe_button.setMinimumSize(QtCore.QSize(0, 30))
        self.pe_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pe_button.setObjectName("pe_button")
        self.horizontalLayout_8.addWidget(self.pe_button)
        self.pb_button = QtWidgets.QPushButton(self.frame_10)
        self.pb_button.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pb_button.setObjectName("pb_button")
        self.horizontalLayout_8.addWidget(self.pb_button)
        self.pva_button = QtWidgets.QPushButton(self.frame_10)
        self.pva_button.setMinimumSize(QtCore.QSize(0, 30))
        self.pva_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pva_button.setObjectName("pva_button")
        self.horizontalLayout_8.addWidget(self.pva_button)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.page_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.image_label = QtWidgets.QLabel(self.frame_11)
        self.image_label.setMinimumSize(QtCore.QSize(392, 392))
        self.image_label.setMaximumSize(QtCore.QSize(392, 392))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_10.addWidget(self.image_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_8 = QtWidgets.QFrame(self.page_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(218, 218, 218);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clear_button = QtWidgets.QPushButton(self.frame_8)
        self.clear_button.setMinimumSize(QtCore.QSize(0, 30))
        self.clear_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_7.addWidget(self.clear_button)
        self.other_button = QtWidgets.QPushButton(self.frame_8)
        self.other_button.setMinimumSize(QtCore.QSize(0, 30))
        self.other_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.other_button.setObjectName("other_button")
        self.horizontalLayout_7.addWidget(self.other_button)
        self.next_button = QtWidgets.QPushButton(self.frame_8)
        self.next_button.setMinimumSize(QtCore.QSize(0, 30))
        self.next_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_7.addWidget(self.next_button)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_select)
        self.page_change = QtWidgets.QWidget()
        self.page_change.setObjectName("page_change")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_change)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.page_change)
        self.frame_9.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_9.setMaximumSize(QtCore.QSize(370, 391))
        self.frame_9.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:2px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid red;\n"
"    color: rgb(191, 191, 191);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_6.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_7.addWidget(self.frame_9, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_change)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(400, 55))
        self.pushButton_4.setMaximumSize(QtCore.QSize(400, 55))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid red;\n"
"    color: rgb(204, 204, 204);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.verticalLayout_8.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_13 = QtWidgets.QFrame(self.page_2)
        self.frame_13.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_13.setMaximumSize(QtCore.QSize(370, 391))
        self.frame_13.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:2px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid red;\n"
"    color: rgb(191, 191, 191);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_9.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_9.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_9.addWidget(self.pushButton_7)
        self.verticalLayout_11.addWidget(self.frame_13, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_close.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_min.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "聚合物裂解模拟计算实验"))
        self.pushButton_home.setText(_translate("MainWindow", "首    页"))
        self.button1.setText(_translate("MainWindow", "选择模型"))
        self.button2.setText(_translate("MainWindow", "参数修改"))
        self.button3.setText(_translate("MainWindow", "计    算"))
        self.button4.setText(_translate("MainWindow", "结果预览"))
        self.button5.setText(_translate("MainWindow", "注    销"))
        self.button6.setText(_translate("MainWindow", "使用帮助"))
        self.label.setText(_translate("MainWindow", "欢迎进入聚合物裂解模拟计算实验！"))
        self.label_6.setText(_translate("MainWindow", "若实验中遇到问题请查看使用帮助！"))
        self.label_2.setText(_translate("MainWindow", "选择你所需要的模型"))
        self.pe_button.setText(_translate("MainWindow", "PE"))
        self.pb_button.setText(_translate("MainWindow", "PB"))
        self.pva_button.setText(_translate("MainWindow", "PVA"))
        self.clear_button.setText(_translate("MainWindow", "清空"))
        self.other_button.setText(_translate("MainWindow", "导入自建模型"))
        self.next_button.setText(_translate("MainWindow", "确定"))
        self.pushButton_1.setText(_translate("MainWindow", "原子坐标文件(data文件)"))
        self.pushButton_2.setText(_translate("MainWindow", "控制文件(In文件)"))
        self.pushButton_3.setText(_translate("MainWindow", "力场文件(ffield文件)"))
        self.pushButton_4.setText(_translate("MainWindow", "开始计算"))
        self.pushButton_5.setText(_translate("MainWindow", "查看分子运动轨迹(dump文件)"))
        self.pushButton_6.setText(_translate("MainWindow", "查看物种文件(species文件)"))
        self.pushButton_7.setText(_translate("MainWindow", "保存结果"))
